version: '3'
services:
  waltz-mariadb:
    build:
      context: mariadb/
      dockerfile: mariadb/Dockerfile
    image: mariadb:waltz-2
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    ports:
      - "3306:3306"
  waltz-web:
    build:
      context: waltz/
      dockerfile: waltz/Dockerfile
    image: waltz:jetty-withldap-2
    environment:
      - DB_HOST=waltz-mariadb
      - DB_USER=root
      - DB_PASSWD=passwd
    links:
      - "waltz-mariadb:waltz-mariadb"
    ports:
      - "8080:8080"